[package]
name = "mantram-parser"
version = "0.1.0"
authors = ["Nico Dinata <nicodnt@icloud.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
